### PR TITLE
30% speed improvement in create_reachability_map

### PR DESCRIPTION
**Pull request by facontidavide**
Hi,

I noticed that the class SphereDiscretization does a lot of unnecessary copies.
Additionally, profiling the code with the command __perf__, I noticed that a surprisingly high number of CPU is used by the instructions __cos__ and __sin__.
I realized that methods like SphereDiscretization::make_sphere_poses call cos() and sin() over and over again with the same angle.

EDIT:

I found even more places where memory from std::vector can be recycled and the call of sin and cos can be avoided.

### CODE REVIEW

**Comment by facontidavide** [comment]
Note.
Similar speed improvements can be achieved in the other map creators.
I leave this as an exercise for the maintainers ;)

**Comment by akgoins** [comment]
@facontidavide, when I try to run the map_creator create_reachability_map node, I am getting a boost out of range error.  I have not tried tracking it down yet, but maybe you can find the problem faster than I can.

**Comment by facontidavide** [comment]
Interesting... it runs just fine on my computer.
I am afraid that I have to ask you to send me the backtrace from GDB.
Do you know how to do that? If not, drop my a line at davide.faconti@gmail.com

**Comment by geoffreychiou** [comment]
I did not get any errors when I ran it.

**Comment by akgoins** [comment]
@facontidavide, here is the backtrace:

#0  0x00007ffff5af9c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff5afd028 in __GI_abort () at abort.c:89
#2  0x00007ffff7af8af9 in boost::assertion::detail::assertion_failed_msg(char const*, char const*, char const*, char const*, long) ()   from /home/alex/reuleaux_ws/devel/lib/libsphere_discretization.so
#3  0x00007ffff7afe024 in boost::array<geometry_msgs::Vector3_<std::allocator<void> >, 10ul>::operator[](unsigned long) ()   from /home/alex/reuleaux_ws/devel/lib/libsphere_discretization.so
#4  0x00007ffff7af1bfb in sphere_discretization::SphereDiscretization::make_sphere_poses(octomath::Vector3 const&, double, std::vector<geometry_msgs::Pose_<std::allocator<void> >, std::allocator<geometry_msgs::Pose_<std::allocator<void> > > >&) ()   from /home/alex/reuleaux_ws/devel/lib/libsphere_discretization.so
#5  0x00000000004310b8 in main ()

**Comment by facontidavide** [comment]
Silly me!

I am surprised that it didn't crash on my machine as well :P 
Just made a commit that fix this stupid error.

Davide

**Comment by akgoins** [comment]
+1.  Thanks for the help!

**Comment by facontidavide** [comment]
Cool.
With this last commit we got a X3 speed improvement compared with the version in October.

**Pull request merged**
