### PR TITLE
Changes to build on ROS Kinetic

### PR DESCRIPTION
**Pull request by geoffreychiou**
@shaun-edwards 
@Jmeyer1292
Please let me know if i'm doing this wrong. We should probably create a branch on the ros-industrial repo for kinetic.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
It looks like this PR contains a lot of (seemingly) unnecessary changes (`HDF5` fi is not the `rosdep` key for the HDF5 dev libs, it's `hdf5` ([here](https://github.com/ros/rosdistro/blob/25d95c0d1caf58012adee9271cc3d3b100819f15/rosdep/base.yaml#L1123))).

Overwriting `CMAKE_CXX_COMPILER`, `CMAKE_CXX_COMPILER_ID` and hard-coding a `link_directories(..)` also doesn't seem like something that would be required to get things to compile under Kinetic?

**Comment by geoffreychiou** [comment]
When I comment out the lines containing CMAKE_CXX_COMPILER and CMAKE_CXX_COMPILER_ID I get the following error:

``
CMakeFiles/load_capability_map.dir/src/load_capability_map.cpp.o: In function `MPI::Intracomm::Intracomm()':
load_capability_map.cpp:(.text._ZN3MPI9IntracommC2Ev[_ZN3MPI9IntracommC5Ev]+0x14): undefined reference to `MPI::Comm::Comm()'
CMakeFiles/load_capability_map.dir/src/load_capability_map.cpp.o: In function `MPI::Intracomm::Intracomm(ompi_communicator_t*)':
load_capability_map.cpp:(.text._ZN3MPI9IntracommC2EP19ompi_communicator_t[_ZN3MPI9IntracommC5EP19ompi_communicator_t]+0x28): undefined reference to `MPI::Comm::Comm()'
CMakeFiles/load_capability_map.dir/src/load_capability_map.cpp.o: In function `MPI::Op::Init(void (*)(void const*, void*, int, MPI::Datatype const&), bool)':
load_capability_map.cpp:(.text._ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb[_ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb]+0x24): undefined reference to `ompi_mpi_cxx_op_intercept'
CMakeFiles/load_capability_map.dir/src/load_capability_map.cpp.o:(.rodata._ZTVN3MPI3WinE[_ZTVN3MPI3WinE]+0x48): undefined reference to `MPI::Win::Free()'
CMakeFiles/load_capability_map.dir/src/load_capability_map.cpp.o:(.rodata._ZTVN3MPI8DatatypeE[_ZTVN3MPI8DatatypeE]+0x78): undefined reference to `MPI::Datatype::Free()'
collect2: error: ld returned 1 exit status
reuleaux/map_creator/CMakeFiles/load_capability_map.dir/build.make:504: recipe for target '/home/gchiou/Projects/Reuleaux/devel/lib/map_creator/load_capability_map' failed
make[2]: *** [/home/gchiou/Projects/Reuleaux/devel/lib/map_creator/load_capability_map] Error 1
CMakeFiles/Makefile2:537: recipe for target 'reuleaux/map_creator/CMakeFiles/load_capability_map.dir/all' failed
make[1]: *** [reuleaux/map_creator/CMakeFiles/load_capability_map.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
``

**Comment by gavanderhoorn** [comment]
Is reuleaux using MPI anywhere? Are you? Perhaps one of the dependencies?

In any case: if MPI is needed, then adding a `find_package(MPI)` or something similar would be miles better than hard coding things. MPI does require you to use their wrappers, but the proposed changes are not portable, and I would not recommend merging them.

**Comment by geoffreychiou** [comment]
Okay, thanks!

**Comment by gavanderhoorn** [comment]
@geoffreychiou: I'm not one of the maintainers of this project. I merely wanted to say that it would seem much better to me to change the `CMakeLists.txt` to properly discover the location of MPI related dependencies, instead of hard-coding them.

Whether the proposed changes are acceptable I'll leave to @shaun-edwards and @Jmeyer1292.

**Comment by gavanderhoorn** [comment]
Perhaps [HDF5 - Building With CMake - Compiling an Application](https://support.hdfgroup.org/HDF5/release/cmakebuild.html#compile) contains some information that could be of help.

**Comment by geoffreychiou** [comment]
@gavanderhoorn You're right, I shouldn't hard code the locations. Jonathan and Shaun probably wouldn't approve of the changes as I have it either. I'll take a look at this again in the morning. Thank you for the advice!

**Comment by shaun-edwards** [comment]
Just an FYI, @akgoins and @jontromanab are contributors/maintainers for this repo.  They should be the ones to approve this PR once it is complete.

**Comment by gavanderhoorn** [comment]
Not sure if related, but ros/rosdistro#13090 recently added `libhdf5-dev` rosdep keys.

**Comment by geoffreychiou** [comment]
I spoke with Alex and we decided I should work on this using Indigo for now.

**Pull request closed without merging**
